### ISSUE TITLE
Code formatting check in CI

### ISSUE THREAD

**Issue by mattnenterprise** [mattnenterprise/rust-imap#48]
@jonhoo I'm thinking it might be a good idea to do some sort of code formatting check with rustfmt in CI.

**Comment by jonhoo** [comment]
We did this in another project I'm involved in: https://github.com/mit-pdos/distributary/pull/31/files#diff-354f30a63fb0907d4ad57269548329e3
I think it's generally a good idea, but the unfortunate thing is that it'll cause false negatives as `rustfmt` gets upgraded and changes the way it formats your code. It shouldn't be *too* bad at this point, since `rustfmt` has gotten decently stable, but it will happen from time to time.

**Comment by jonhoo** [comment]
I'm still trying to figure out if this is something we want as `rustfmt` does occasionally change it's mind about style... :/

**Comment by jonhoo** [comment]
Let's move further discussion to https://github.com/jonhoo/rust-imap/issues/48.
