### ISSUE TITLE
0.7.0 examples are out of date

### ISSUE THREAD

**Issue by TsarFox** [mattnenterprise/rust-imap#67]
Attempting to compile the example code in `README.md` with version 0.7.0 of the library yields the following compiler output:

```
error[E0599]: no method named `capability` found for type `imap::client::Client<native_tls::TlsStream<std::net::TcpStream>>` in the current scope
  --> src/main.rs:19:23
   |
19 |     match imap_socket.capability() {
   |                       ^^^^^^^^^^
   |
   = help: did you mean `capabilities`?

error[E0277]: `imap::Fetch` doesn't implement `std::fmt::Display`
  --> src/main.rs:38:30
   |
38 |                 print!("{}", line);
   |                              ^^^^ `imap::Fetch` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
   |
   = help: the trait `std::fmt::Display` is not implemented for `imap::Fetch`
   = note: required because of the requirements on the impl of `std::fmt::Display` for `&imap::Fetch`
   = note: required by `std::fmt::Display::fmt`

error: aborting due to 2 previous errors

error: Could not compile `comptest`.
```

Documentation of this new library interface would be very helpful; I switched to 0.6.0 this morning after a frustrating night of trying to figure out 0.7.0

**Comment by jonhoo** [comment]
Ouch, yeah, that would be annoying. Good catch!
I'll try to take a look at this today. Ideally we should use [`cargo-readme`](https://github.com/livioribeiro/cargo-readme) so that we can move the example into the documentation in `src/lib.rs`. That would make it run as a doctest so we could ensure it doesn't break in the future.

For what it's worth, the errors above are fixed by a) using `imap_socket.capabilities()` (I didn't even know we'd changed the name of that method); and b) using `{:?}` to use the [debug output of `Fetch`](https://docs.rs/imap/0.7.0/imap/struct.Fetch.html#impl-Debug). This latter change is because we used to just return the raw strings that the server gives you when you fetched messages, but we now instead return a `Fetch` object which holds more structured content (and thus can't directly be printed) :)
